apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "harbor.fullname" . }}-registry"
data:
  config.yml: |+
    version: 0.1
    log:
      level: info
      fields:
        service: registry
    storage:
        cache:
            layerinfo: inmemory
        filesystem:
            rootdirectory: /var/lib/registry
        maintenance:
            uploadpurging:
                enabled: false
        delete:
            enabled: true
    http:
        addr: :5000
        secret: placeholder
        debug:
            addr: localhost:5001
    auth:
      token:
        issuer: harbor-token-issuer
        realm: "https://{{ .Values.ingress.url }}/service/token"
        rootcertbundle: /etc/registry/root.crt
        service: harbor-registry

    notifications:
      endpoints:
        - name: harbor
          disabled: false
          url: http://{{ template "harbor.fullname" . }}-ui/service/notifications
          timeout: 3000ms
          threshold: 5
          backoff: 1s
